### ISSUE TITLE
Are amines double-counted?

### ISSUE THREAD

**Issue by Aariq** [Meredith-Lab/volcalc#49]
primary, secondary, and tertiary amines are already included in `calc_vol()` with coefficients and then this line also adds a coefficient for amines.  Doesn't that double-count amines? 

https://github.com/Meredith-Lab/volcalc/blob/9e7250a9462224659766546efc1937236c07908b/R/calc_vol.R#L93C26-L93C26

**Comment by Aariq** [comment]
Ok, good to know.  I'll hold off on fixing this until after we get through currently open PRs.  The next PR will hopefully include more tests for `get_fx_groups()` that will catch this kind of thing. 

@ledfordmarshall—FYI,numbers might be *slightly* off for amines.

**Comment by KristinaRiemer** [comment]
There's a little conversation about this in the manuscript, linked to the "Amine" in the coefficients table.

**Comment by Aariq** [comment]
On second though, maybe we should deal with this and release a v1.0.2 before big breaking changes get merged.  Any preference?
