### ISSUE TITLE
Document solutions to openbabel dependency install

### ISSUE THREAD

**Issue by KristinaRiemer** [Meredith-Lab/volcalc#7]
Right now, installing the C library openbabel which the R package ChemmineOB depends upon can be painful. Need to determine a way to make this easier. Or possibly have use of it within volcalc optional?

**Comment by Aariq** [comment]
Might be worthwhile to check out [`pak`](https://pak.r-lib.org/).  It supposedly lists missing system dependencies in a human readable way instead of failing.  Works with github installs too. Could be better to put in the README instead of `remotes::install_github()`

e.g.
```
pak::pkg_install("Meredith-Lab/volcalc")
```

**Comment by Aariq** [comment]
Once we know the magic to install openbabel on different platforms, we should submit that info to this repo: https://github.com/rstudio/r-system-requirements

That will allow installation to "just work" with `pak` and the github action `r-lib/actions/setup-r-dependencies`

**Comment by Aariq** [comment]
Useful sites for figuring out how to install openbabel:

https://pkgs.org/download/openbabel
https://packages.ubuntu.com/mantic/openbabel

**Comment by Aariq** [comment]
Made a PR to r-system-requirements: https://github.com/rstudio/r-system-requirements/pull/140

**Comment by Aariq** [comment]
Instructions are in README now
