### ISSUE TITLE
r-universe builds on macOS failing

### ISSUE THREAD

**Issue by Aariq** [Meredith-Lab/volcalc#74]
r-universe builds of `volcalc` on macOS are failing, which is puzzling since it works on my mac and on our GitHub actions with macOS. Looks like a `ChemmineOB` installation issue: https://github.com/r-universe/cct-datascience/actions/runs/6354874446/job/17569286604

**Comment by Aariq** [comment]
I suspect examples might be failing because `OpenBabel` isn't included in the macOS version of `ChemmineOB` the way it is in the Windows version (confusing because the error message says ChemmineOB isn't available on Windows--an apparent bug).  I don't think there is much we can do about this (see discussion [here](https://github.com/r-universe-org/help/discussions/99#discussioncomment-1899516)), but this will also be a problem with CRAN it seems.  May need to conditionally skip running tests and examples on non-windows OS when OpenBabel isn't installed and [pre-compute vignettes](https://ropensci.org/blog/2019/12/08/precompute-vignettes/) to avoid this build failure.

**Comment by Aariq** [comment]
Might just be that I need to copy the `SystemRequirements` field from `ChemmineOB`.

**Comment by Aariq** [comment]
Opened an issue with r-universe: https://github.com/r-universe-org/help/issues/329

**Comment by Aariq** [comment]
Currently this issue might be causing this problem: https://github.com/girke-lab/ChemmineOB/issues/35

**Comment by barracuda156** [comment]
@Aariq Here is the fix: https://github.com/girke-lab/ChemmineOB/issues/35#issuecomment-2094885763

**Comment by Aariq** [comment]
Going to close this as there's nothing we can do about it in `volcalc`
