### ISSUE TITLE
Include better example .mol files in inst/extdata

### ISSUE THREAD

**Issue by Aariq** [Meredith-Lab/volcalc#79]
The current example mol files in `inst/extdata/` are maybe not the best examples:

- C00011.mol is CO2
- C00042.mol is succinate
-  C16181.mol is a chlorinated hydrocarbon

I think it would be good to replace these with more biologically relevant compounds that span a greater range of volatility.

Ideas:
- Isoprene (highly volatile plant VOC)
- Jasmonic acid (moderately volatile fatty acid derivative)
- Geosmin (microbial sesquiterpene)
- Glucose (non-volatile)

**Comment by Aariq** [comment]
Thoughts @ledfordmarshall @laurameredith?

**Comment by Aariq** [comment]
Or maybe I'm being too much of a biologist here and there are better example compounds that span fields better.

**Comment by laurameredith** [comment]
Those are great examples, I like those
